extends: airbnb-base
# overrides: []

env:
  node: true
  commonjs: true
  es2022: true
  browser: false
  jest: true

parserOptions:
  ecmaVersion: 13

rules:
  consistent-return: 0
  global-require: 0
  import/no-extraneous-dependencies: 0
  no-await-in-loop: 0
  no-console: 0
  no-param-reassign: 0
  no-throw-literal: 0
