version: '3.9'

volumes:
  postgis-data:
services:
  db:
    image: kartoza/postgis:15-3.3
    volumes:
      - postgis-data:/var/lib/postgres-demo
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DB=users
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=plpgsql,uuid-ossp
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      - service-network

networks:
  service-network:
