version: '3'

services:

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test_pass'
    networks:
      - service

networks:
  service: