version: "3"
services:

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongodb-demo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      # - MONGO_INITDB_DATABASE=admin
    # networks:
      # - node-webapp-network
# networks:
  # node-webapp-network:
    # driver: bridge